### ISSUE TITLE
trying to deploy a fork of this project to my own google cloud account.

### ISSUE THREAD

**Issue by sketchbook22** [simasch/vaadin-appengine-demo#2]
I read through your blog: https://martinelli.ch/how-to-deploy-a-vaadin-application-to-google-cloud-app-engine/
I read through the README on this github.
and I gave it a try...  here are the steps I have come up with after some trial and error.

1.  enable Google App Engine on my account
2.  double check your billing is fine, or that may lead to misleading permission errors
3.  start a Google App Engine project
4.  enable some more things as described here: 
5.  https://cloud.google.com/build/docs/deploying-builds/deploy-appengine
6.  Fork your repo and git clone to my local machine
7.  change the <projectId></projectId> value in the pom.xml to point to the google cloud project.  lets call it mytestproject  (if you don't do this you will get permission errors)
8.  start docker desktop since the build process will be expecting it.
9.  `mvnw package appengine:deploy -Pproduction`
10. see a successful message: [INFO] GCLOUD: To view your application in the web browser run:
[INFO] GCLOUD:   $ gcloud app browse --project=mytestproject

can't say much about what user configuration and permissions configurations are required since i tried a bunch of stuff that wasn't necessary for permissions when the problem was elsewhere.

Took me quite a bit of debugging to get here but now the project is on the google cloud, and I go to visit it in the browser, and all I see is:  "Service Unavailable"

not really sure where i went wrong.  i guess next ill try to run the app from my local machine to see what it should have looked like... but if it works locally I'm not sure what could be wrong with the cloud deployment.

**Comment by sketchbook22** [comment]
Update:
Attempted a local build (see below), and now I have some idea of what I need to fix, 
not exactly sure which part of the application's configuration, but it is a start.


`mvnw -Dspring.profiles.active=dev`

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to bind properties under 'spring.datasource.url' to java.lang.String:
> 
>     Property: spring.datasource.url
>     Value: "${sm://neon-vaadin-jooq-url}"
>     Origin: class path resource [application.properties] - 15:23
>     Reason: java.lang.IllegalArgumentException: The GCP Secret Manager project id must not be empty: sm://neon-vaadin-jooq-url
> 
> Action:
> 
> Update your application's configuration
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
>

**Comment by sketchbook22** [comment]
Found and enabled GCP secret manager in the Google Cloud interface...
and I gather I would need to add a property named neon-vaadin-jooq-url, but i don't know what value it should be, I suppose a matching value is around here in another config somewhere.
i see the compose.yml used to spin up the database,  I wonder what jooq is... (checks google, yup that is related to the database)
i suddenly recall you mentioning hosting the database on neon.
I suppose I haven't done anything on the neon side yet...

sorry thinking out loud.

**Comment by sketchbook22** [comment]
ok signed up for neon, made a project, it gave me a url with i replaced the ******* part of that url with my password and put that url into google secrets manager...  (so far I'm not a fan of the browser interface for google cloud, it can definitely do a lot more than I need it to, and I often feel lost in a maze)

none of that changed the error I seen, because the error was trying to tell me I should run this command.
`gcloud config set project mytestproject`

which then tells me I should run 
`gcloud auth application-default set-quota-project mytestproject`

which also offered to enable cloudresourcemanager for me through the command prompt

trying another local build
`mvnw -Dspring.profiles.active=dev`

> ERROR 23388 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception with message: URL must start with 'jdbc'

:(

**Comment by sketchbook22** [comment]
updated my neon-vaadin-jooq-url in google cloud secrets
prefixing it with jdbc:

> Factory method 'flyway' threw exception with message: Driver org.postgresql.Driver claims to not accept jdbcUrl

found somewhere it should be formatted like this
jdbc:postgresql://<host>:<port>/<dbname>?user=<username>&password=<password>

> FlywayConfiguration.class]: Unable to obtain connection from database: ERROR: password authentication failed for user

neon requires a password with special characters, and i have yet to find a password that works.
i see neon supports api keys, so i created one of those, not sure where to use it in the url though.
also i see the original url says sslmode=require so i'm not sure why it had username and ******* in it to begin with.
i'm probably going about this all wrong,  but i suspect what i need to change is the value of my google cloud secret: neon-vaadin-jooq-url I'm just not sure what format it should be in.

It feels like I'm close to having my fork of this demo project hosted.
I really appreciate that this demo project exists, I just wish I knew enough to get it off the ground.

I'll probably try more on Monday.

I guess i should look around and turn cloud things off or scale them down or whatever before i go.

**Comment by simasch** [comment]
the format of the URL must be a valid JDBC URL starting with jdbc:
